#!/usr/bin/env node
/**
 * Stage 3 — offline. Turns the exported SVGs in design/icons/ into one typed React
 * module at src/components/icons/generated.tsx.
 *
 * Why generate rather than hand-write: there are 53 icons, they are redrawn in
 * Figma, and `npm run figma:icons` re-exports them wholesale. A hand-maintained
 * copy would drift on the first redraw and nobody would notice which of the 53
 * moved. Regenerating is one command and the diff is the review.
 *
 * The exports carry the fill they happened to be rendered with — usually Grey/100
 * `#1A1A1A`, but a handful sit on legacy `#808080`, which CLAUDE.md forbids
 * porting. Rewriting every literal fill to `currentColor` both makes the icons
 * themeable and erases that legacy colour at the door.
 *
 * Usage:  npm run figma:components
 */
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises'
import { exit } from 'node:process'
import { DESIGN_DIR } from './lib.mjs'

const ICONS_DIR = new URL('icons/', DESIGN_DIR)
const OUT = new URL('../../src/components/icons/generated.tsx', import.meta.url)

/** `heart-outline` -> `HeartOutline`, giving `<HeartOutlineIcon />`. */
const pascal = (slug) =>
  slug.split(/[^a-z0-9]+/i).filter(Boolean).map((p) => p[0].toUpperCase() + p.slice(1)).join('')

let files
try {
  files = (await readdir(ICONS_DIR)).filter((f) => f.endsWith('.svg')).sort()
} catch {
  console.error('design/icons/ has no exports yet. Run `npm run figma:icons` first.')
  exit(1)
}
if (!files.length) {
  console.error('design/icons/ contains no SVGs. Run `npm run figma:icons` first.')
  exit(1)
}

const components = []
for (const file of files) {
  const slug = file.replace(/\.svg$/, '')
  const raw = await readFile(new URL(file, ICONS_DIR), 'utf8')

  const body = raw
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    // Any literal colour becomes the text colour; `fill="none"` is structural and stays.
    .replace(/fill="(?!none")[^"]*"/g, 'fill="currentColor"')
    .replace(/stroke="(?!none")[^"]*"/g, 'stroke="currentColor"')
    // Hyphenated SVG attributes become JSX camelCase. Anchored to attribute
    // position (whitespace before, `=` after) so it can never reach inside a `d`
    // path, where a stray rewrite would silently deform the glyph.
    .replace(/(\s)([a-z]+)-([a-z])([a-z]*=)/g, (_, ws, a, b, rest) => `${ws}${a}${b.toUpperCase()}${rest}`)
    .trim()

  const viewBox = raw.match(/viewBox="([^"]*)"/)?.[1] ?? '0 0 24 24'
  components.push({ name: `${pascal(slug)}Icon`, slug, viewBox, body })
}

const source = `/*
 * GENERATED by \`npm run figma:components\` from design/icons/*.svg — do not edit.
 *
 * These are the ${components.length} \`Element / Icon / *\` components from Figma
 * \`gDoteM1ow1AZpSEGSNhpc7\`, the set that replaces \`lucide-react\` (decision #4).
 * Every fill is \`currentColor\`, so an icon takes the colour of the text around it;
 * size with \`className\` (\`h-6 w-6\` is the design's 24px default).
 */
import type { SVGProps } from 'react'

export type IconProps = SVGProps<SVGSVGElement>

${components
  .map(
    ({ name, viewBox, body }) => `export function ${name}(props: IconProps) {
  return (
    <svg viewBox="${viewBox}" fill="none" aria-hidden focusable={false} {...props}>
      ${body.split('\n').map((l) => l.trim()).filter(Boolean).join('\n      ')}
    </svg>
  )
}`,
  )
  .join('\n\n')}
`

await mkdir(new URL('./', OUT), { recursive: true })
await writeFile(OUT, source)
console.log(`Wrote ${components.length} icon components to src/components/icons/generated.tsx`)
