/**
 * Shared helpers for the Figma snapshot pipeline.
 *
 * The pipeline is split in two on purpose: `pull.mjs` is the only stage that
 * touches the network, and everything downstream is a pure function of the raw
 * JSON it writes. That split is what makes the rate limit survivable — the
 * expensive call happens once a month, and every later question is answered
 * from disk.
 *
 * See design/README.md for the whole rationale.
 */
import { env } from 'node:process'

export const FILE_KEY = 'gDoteM1ow1AZpSEGSNhpc7'

/**
 * Both roots are overridable so a run can be pointed at a scratch directory —
 * used by the tests, and handy for extracting somewhere else to diff before
 * overwriting the committed snapshot.
 */
const dir = (envVar, fallback) => {
  const override = env[envVar]
  if (!override) return new URL(fallback, import.meta.url)
  return new URL(override.endsWith('/') ? override : `${override}/`, 'file://')
}

/** Raw API responses. Big, ephemeral, gitignored — regenerated by `figma:pull`. */
export const RAW_DIR = dir('FIGMA_RAW_DIR', '../../.figma-raw/')
/** Derived artifacts. Small, committed, the thing everyone actually reads. */
export const DESIGN_DIR = dir('FIGMA_DESIGN_DIR', '../../design/')

/** "69h 8m" / "4m 9s" — a wait you can act on rather than a raw second count. */
export function formatDuration(seconds) {
  if (!Number.isFinite(seconds) || seconds < 0) return 'unknown'
  const d = Math.floor(seconds / 86400)
  const h = Math.floor((seconds % 86400) / 3600)
  const m = Math.floor((seconds % 3600) / 60)
  const s = Math.floor(seconds % 60)

  if (d > 0) return `${d}d ${h}h`
  if (h > 0) return `${h}h ${m}m`
  if (m > 0) return `${m}m ${s}s`
  return `${s}s`
}

/**
 * Reads the rate-limit story off a 429's headers.
 *
 * `Retry-After` is real here and is in **seconds**, per RFC — verified 2026-08-03
 * by sampling it 61 seconds apart and watching it fall by 64. It is a true
 * countdown: repeated requests do not reset it, so probing costs nothing but
 * also buys nothing.
 *
 * Figma exposes it deliberately, alongside the plan tier and which limit was
 * tripped — see `access-control-expose-headers` on any 429.
 */
export function readRateLimit(headers) {
  const raw = headers.get('retry-after')
  // RFC allows an HTTP-date instead of a delta; Figma sends a delta, but a date
  // would otherwise parse as NaN and read as "unknown" forever.
  let seconds = raw === null ? null : Number(raw)
  if (raw !== null && Number.isNaN(seconds)) {
    const at = Date.parse(raw)
    seconds = Number.isNaN(at) ? null : Math.max(0, Math.round((at - Date.now()) / 1000))
  }

  return {
    seconds,
    readableWait: seconds === null ? 'unknown' : formatDuration(seconds),
    resetsAt: seconds === null ? null : new Date(Date.now() + seconds * 1000),
    planTier: headers.get('x-figma-plan-tier'),
    limitType: headers.get('x-figma-rate-limit-type'),
    upgradeLink: headers.get('x-figma-upgrade-link'),
  }
}

/**
 * Figma throttles per endpoint *family* and the budget is inherited across
 * sessions — a fresh container can get a 429 on its first ever call. Retrying in
 * a loop does not help, and now it does not have to be guesswork either: the
 * 429 carries `Retry-After`, so this reports exactly how long is left.
 */
export async function figmaFetch(path, { token = env.FIGMA_ACCESS_TOKEN } = {}) {
  if (!token) {
    throw new Error(
      'FIGMA_ACCESS_TOKEN is not set. It lives in the environment config, never in the repo.',
    )
  }

  const res = await fetch(`https://api.figma.com/v1/${path}`, {
    headers: { 'X-Figma-Token': token },
  })

  if (res.status === 429) {
    const limit = readRateLimit(res.headers)
    const until = limit.resetsAt ? ` (about ${limit.resetsAt.toISOString().slice(0, 16)}Z)` : ''
    const err = new Error(
      `Figma returned 429 for /${path}.\n` +
        `Retry-After says ${limit.readableWait} left${until}.\n` +
        `Plan tier: ${limit.planTier ?? 'unknown'}; limit tripped: ${limit.limitType ?? 'unknown'}.\n` +
        'That is a real countdown, not a suggestion — repeated requests do not reset it and\n' +
        'do not shorten it. Everything else in this pipeline works offline from design/.',
    )
    err.rateLimited = true
    err.rateLimit = limit
    throw err
  }
  if (!res.ok) throw new Error(`Figma returned ${res.status} for /${path}: ${await res.text()}`)

  return res.json()
}

const channel = (v) => Math.round(v * 255).toString(16).padStart(2, '0').toUpperCase()

/**
 * Figma stores opacity as float32, so a designer's 70% arrives as 0.69999999 and
 * would render as B2 rather than the intended B3. Snap to the authored percent.
 */
export function toHex(color, opacity = 1) {
  const rgb = `#${channel(color.r)}${channel(color.g)}${channel(color.b)}`
  const authored = Math.round(opacity * 100) / 100
  return authored >= 0.999 ? rgb : `${rgb}${channel(authored)}`
}

/**
 * CSS gradient angle from Figma's two gradient handles.
 *
 * Handles are normalised to the node's bounding box, so this is only the literal
 * visual angle on a square node — on any other aspect ratio CSS and Figma disagree,
 * which is why the raw handles are kept alongside the computed value.
 */
function gradientAngle([start, end]) {
  const angle = (Math.atan2(end.x - start.x, -(end.y - start.y)) * 180) / Math.PI
  return Math.round(((angle % 360) + 360) % 360)
}

/** Resolves one Figma paint to something a stylesheet can be written from. */
export function resolvePaint(paint) {
  if (paint.visible === false) return null
  const opacity = paint.opacity ?? 1

  if (paint.type === 'SOLID') {
    return { type: 'SOLID', color: toHex(paint.color, paint.color.a ?? opacity) }
  }

  if (paint.type?.startsWith('GRADIENT')) {
    return {
      type: paint.type,
      angle: paint.gradientHandlePositions ? gradientAngle(paint.gradientHandlePositions) : null,
      handles: paint.gradientHandlePositions ?? null,
      stops: (paint.gradientStops ?? []).map((s) => ({
        position: Math.round(s.position * 1e4) / 1e4,
        color: toHex(s.color, s.color.a ?? 1),
      })),
    }
  }

  // Image fills are referenced, never fetched. The file's image fills include
  // personal photographs — see design/README.md §Privacy.
  if (paint.type === 'IMAGE') {
    return { type: 'IMAGE', imageRef: paint.imageRef ?? null, scaleMode: paint.scaleMode ?? null }
  }

  return { type: paint.type }
}

/**
 * Layout and geometry properties worth carrying. Everything omitted here is
 * either derivable, always-default, or vector path data — and vector geometry is
 * the overwhelming bulk of a Figma file, which is what makes the snapshot small
 * enough to commit.
 */
const CARRIED = [
  'layoutMode', 'layoutWrap', 'itemSpacing', 'counterAxisSpacing',
  'paddingLeft', 'paddingRight', 'paddingTop', 'paddingBottom',
  'primaryAxisAlignItems', 'counterAxisAlignItems',
  'primaryAxisSizingMode', 'counterAxisSizingMode',
  'layoutSizingHorizontal', 'layoutSizingVertical',
  'layoutAlign', 'layoutGrow', 'clipsContent',
  'cornerRadius', 'rectangleCornerRadii', 'strokeWeight', 'strokeAlign',
  'opacity', 'blendMode', 'isMask', 'visible',
]

const round = (n) => (typeof n === 'number' ? Math.round(n * 100) / 100 : n)

/**
 * Collapses one raw node to the fields an implementer needs, resolving style and
 * component ids to names so the committed JSON reads on its own without a lookup
 * table beside it.
 */
export function pruneNode(node, { styles = {}, components = {}, componentSets = {} } = {}) {
  const out = { id: node.id, name: node.name, type: node.type }

  const box = node.absoluteBoundingBox
  if (box) {
    out.box = { x: round(box.x), y: round(box.y), w: round(box.width), h: round(box.height) }
  }

  for (const key of CARRIED) {
    const value = node[key]
    if (value === undefined) continue
    // `visible` and `blendMode` are noisy at their defaults; only carry deviations.
    if (key === 'visible' && value === true) continue
    if (key === 'blendMode' && value === 'PASS_THROUGH') continue
    if (key === 'opacity' && value === 1) continue
    out[key] = typeof value === 'number' ? round(value) : value
  }

  /**
   * Rotation is absent from the bounding box, which grows to contain a rotated
   * node — so without it a fanned card stack reads as three differently-sized
   * cards. Stored in **degrees, clockwise-positive**: Figma reports radians
   * counter-clockwise, but every consumer of this snapshot is writing CSS, and
   * rounding raw radians to the shared 2dp turned an exact 2° into 1.7°.
   * `.figma-raw/` is gitignored and rebuilt per session, so a value not carried
   * here cannot be recovered offline.
   */
  if (node.rotation) out.rotation = round((-node.rotation * 180) / Math.PI)

  const fills = (node.fills ?? []).map(resolvePaint).filter(Boolean)
  if (fills.length) out.fills = fills

  const strokes = (node.strokes ?? []).map(resolvePaint).filter(Boolean)
  if (strokes.length) out.strokes = strokes

  if (node.effects?.length) {
    out.effects = node.effects
      .filter((e) => e.visible !== false)
      .map((e) => ({
        type: e.type,
        radius: round(e.radius),
        offset: e.offset ? { x: round(e.offset.x), y: round(e.offset.y) } : undefined,
        spread: e.spread ? round(e.spread) : undefined,
        color: e.color ? toHex(e.color, e.color.a ?? 1) : undefined,
      }))
    if (!out.effects.length) delete out.effects
  }

  // The token layer. Style *names* are the whole reason this project can read its
  // design system without the Enterprise-only Variables API, so resolve them here
  // rather than leaving opaque ids in the snapshot.
  const refs = node.styles ?? {}
  const named = {}
  for (const [slot, id] of Object.entries(refs)) {
    if (styles[id]?.name) named[slot] = styles[id].name
  }
  if (Object.keys(named).length) out.styles = named

  if (node.type === 'TEXT') {
    if (node.characters) out.characters = node.characters
    if (node.style) {
      const { fontFamily, fontSize, fontWeight, lineHeightPx, letterSpacing, textAlignHorizontal,
        textAlignVertical, textCase, textDecoration } = node.style
      out.text = {
        fontFamily, fontSize, fontWeight,
        lineHeightPx: round(lineHeightPx),
        letterSpacing: round(letterSpacing),
        textAlignHorizontal, textAlignVertical, textCase, textDecoration,
      }
      for (const k of Object.keys(out.text)) if (out.text[k] === undefined) delete out.text[k]
    }
  }

  if (node.componentId) {
    out.componentId = node.componentId
    const meta = components[node.componentId]
    if (meta?.name) out.component = meta.name
    if (meta?.componentSetId && componentSets[meta.componentSetId]?.name) {
      out.componentSet = componentSets[meta.componentSetId].name
    }
  }
  if (node.componentPropertyDefinitions) {
    out.componentPropertyDefinitions = node.componentPropertyDefinitions
  }
  if (node.componentProperties) out.componentProperties = node.componentProperties

  if (node.children?.length) {
    out.children = node.children.map((child) =>
      pruneNode(child, { styles, components, componentSets }),
    )
  }

  return out
}

/** Depth-first walk over a raw or pruned tree. */
export function* walk(node) {
  yield node
  for (const child of node.children ?? []) yield* walk(child)
}

/**
 * Resolves `Element / Icon / *` name collisions the file walk can produce
 * (PD-261). A scratch instance dropped into an unrelated frame — e.g. `AI /
 * Clubs one screen / 2026-08-17` re-used `Chevron Down` and `Chevron Right` —
 * carries the same name as the real component and walks after it, so keying
 * on name with "last one wins" silently replaces the canonical component with
 * an INSTANCE the render endpoint may not export at all (loud: `figma:icons`
 * prints `Missing:`) or exports as a byte-identical but wrong-sourced SVG
 * (quiet: `components.mjs` rewrites every fill to `currentColor`, so nothing
 * in `generated.tsx` changes).
 *
 * A COMPONENT or COMPONENT_SET always outranks an INSTANCE sharing its name,
 * regardless of walk order. Within the same rank, last walked still wins —
 * that was always the tie-break between two real components (or two
 * instances) sharing a name, and nothing here changes it.
 *
 * Returns the resolved icon per name, plus every name more than one node
 * claimed, so the caller can print what it chose instead of resolving
 * silently.
 */
export function resolveIconCollisions(icons) {
  const rankOf = (type) => (type === 'COMPONENT' || type === 'COMPONENT_SET' ? 0 : 1)

  const byName = new Map()
  const candidatesByName = new Map()

  for (const icon of icons) {
    if (!candidatesByName.has(icon.name)) candidatesByName.set(icon.name, [])
    candidatesByName.get(icon.name).push(icon)

    const existing = byName.get(icon.name)
    // A candidate wins if it outranks the current holder, or ties it — the
    // tie case is what preserves "last walked wins" for same-rank nodes.
    if (!existing || rankOf(icon.type) <= rankOf(existing.type)) {
      byName.set(icon.name, icon)
    }
  }

  const resolved = [...byName.values()].sort((a, b) => a.name.localeCompare(b.name))
  const collisions = [...candidatesByName.entries()]
    .filter(([, candidates]) => candidates.length > 1)
    .map(([name, candidates]) => ({ name, chosen: byName.get(name), candidates }))

  return { resolved, collisions }
}

/**
 * Counts how often each named paint and text style is used, and with which
 * resolved value. The dominant value is the token; a style resolving to more
 * than one value means the file has drifted and is worth surfacing.
 */
export function collectTokens(root, styles) {
  const fills = new Map()
  const text = new Map()

  const bump = (map, name, value) => {
    if (!map.has(name)) map.set(name, new Map())
    const counts = map.get(name)
    counts.set(value, (counts.get(value) ?? 0) + 1)
  }

  for (const node of walk(root)) {
    const refs = node.styles ?? {}

    if (refs.fill && styles[refs.fill]) {
      for (const paint of node.fills ?? []) {
        if (paint.type !== 'SOLID' || paint.visible === false) continue
        bump(fills, styles[refs.fill].name, toHex(paint.color, paint.opacity ?? paint.color.a ?? 1))
      }
    }

    if (refs.text && styles[refs.text] && node.style) {
      const { fontSize, lineHeightPx, fontWeight } = node.style
      // Line height arrives as float32 noise (20.00004 for an authored 20), which
      // would otherwise land verbatim in the token table.
      bump(text, styles[refs.text].name, `${round(fontSize)}/${round(lineHeightPx)}/${fontWeight}`)
    }
  }

  return { fills, text }
}

/** Census of the geometry values actually used, so primitives stop being guessed. */
export function collectGeometry(root) {
  const census = { cornerRadius: {}, itemSpacing: {}, paddingLeft: {}, paddingTop: {} }

  for (const node of walk(root)) {
    for (const key of Object.keys(census)) {
      const value = node[key]
      if (typeof value !== 'number') continue
      census[key][value] = (census[key][value] ?? 0) + 1
    }
  }

  // Descending by use — the most-used value is the one a new component should take.
  return Object.fromEntries(
    Object.entries(census).map(([key, counts]) => [
      key,
      Object.entries(counts)
        .map(([value, n]) => ({ value: Number(value), n }))
        .sort((a, b) => b.n - a.n),
    ]),
  )
}

export const total = (counts) => [...counts.values()].reduce((a, b) => a + b, 0)
export const dominant = (counts) => [...counts.entries()].sort((a, b) => b[1] - a[1])[0][0]
export const isLegacy = (name) => name.includes('(OLD)')

/** Filesystem-safe, stable, and readable — `v2 / Component / Button` -> `v2-component-button`. */
export function slug(name) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80) || 'unnamed'
}

// ---- Render templates for the two committed generated artifacts -------------
//
// These live here, rather than inline in `extract.mjs` and `components.mjs`,
// for one reason: `scripts/figma/__tests__/generated-artifacts.test.mjs` calls
// them to rebuild `design/TOKENS.md` and `src/components/icons/generated.tsx`
// from the committed sources and byte-compares. A test holding its own copy of
// the template would be a second definition that drifts, and a staleness alarm
// that has drifted from the generator it checks is worse than none — it goes
// green against the wrong artifact.
//
// Both are PURE functions of their arguments. Do not read the filesystem, the
// clock or the network from here, or the rebuild stops being reproducible.

/**
 * `design/TOKENS.md`, from the same arrays `extract.mjs` writes to
 * `design/tokens.json`. Reproduces the shape of the token tables in
 * `docs/reference/design-system.md` so drift between the two is a plain `diff`.
 */
export function renderTokensTable({ fileKey, lastModified, colors, type, legacy }) {
  return [
    '# Design tokens — generated by `npm run figma:extract`',
    '',
    'Do not hand-edit. Regenerate from the snapshot; if this disagrees with',
    // Points at docs/reference/design-system.md, NOT `CLAUDE.md` §Design
    // System. It said the latter until 2026-08-16, three sessions after the
    // tables moved out of CLAUDE.md — so the committed TOKENS.md (hand-corrected
    // to the new path) and this template disagreed, and the next
    // `npm run figma:extract` would have silently reinstated the dead pointer.
    // Found by `scripts/figma/__tests__/generated-artifacts.test.mjs` on its
    // first run, which is the whole argument for that test.
    '`docs/reference/design-system.md`, this file is right and that one is stale.',
    '',
    `Figma file \`${fileKey}\`, last modified ${lastModified ?? 'unknown'}.`,
    '',
    '**Colors:**',
    '',
    '| Token | Value | n |',
    '|---|---|---|',
    ...colors.map((c) => `| \`${c.name}\` | \`${c.value}\` | ${c.n} |`),
    '',
    '**Type — Poppins:**',
    '',
    '| Token | Size / LH | Weight | n |',
    '|---|---|---|---|',
    ...type.map((t) => `| \`${t.name}\` | ${t.fontSize} / ${t.lineHeight} | ${t.fontWeight} | ${t.n} |`),
    '',
    `**Legacy v1 styles still live inside v2 components: ${legacy.length}.** Do not port these;`,
    'resolve to the v2 token nearest in intent.',
    '',
    '| Token | Value | n |',
    '|---|---|---|',
    ...legacy.map((c) => `| \`${c.name}\` | \`${c.value}\` | ${c.n} |`),
    '',
  ].join('\n')
}

/** `heart-outline` -> `HeartOutline`, giving `<HeartOutlineIcon />`. */
const pascal = (s) =>
  s.split(/[^a-z0-9]+/i).filter(Boolean).map((p) => p[0].toUpperCase() + p.slice(1)).join('')

/**
 * One exported SVG -> the pieces `renderIconModule` needs. `filename` is the
 * `design/icons/` entry (`heart-outline.svg`); `raw` is its contents.
 */
export function svgToIconComponent(filename, raw) {
  const name = filename.replace(/\.svg$/, '')

  const body = raw
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    // Any literal colour becomes the text colour; `fill="none"` is structural and stays.
    .replace(/fill="(?!none")[^"]*"/g, 'fill="currentColor"')
    .replace(/stroke="(?!none")[^"]*"/g, 'stroke="currentColor"')
    // Hyphenated SVG attributes become JSX camelCase. Anchored to attribute
    // position (whitespace before, `=` after) so it can never reach inside a `d`
    // path, where a stray rewrite would silently deform the glyph.
    .replace(/(\s)([a-z]+)-([a-z])([a-z]*=)/g, (_, ws, a, b, rest) => `${ws}${a}${b.toUpperCase()}${rest}`)
    .trim()

  return {
    name: `${pascal(name)}Icon`,
    slug: name,
    viewBox: raw.match(/viewBox="([^"]*)"/)?.[1] ?? '0 0 24 24',
    body,
  }
}

/** `src/components/icons/generated.tsx`, from `svgToIconComponent` output. */
export function renderIconModule(components) {
  return `/*
 * GENERATED by \`npm run figma:components\` from design/icons/*.svg — do not edit.
 *
 * These are the ${components.length} \`Element / Icon / *\` components from Figma
 * \`${FILE_KEY}\`, the set that replaces \`lucide-react\` (decision #4).
 * Every fill is \`currentColor\`, so an icon takes the colour of the text around it;
 * size with \`className\` (\`h-6 w-6\` is the design's 24px default).
 */
import type { SVGProps } from 'react'

export type IconProps = SVGProps<SVGSVGElement>

${components
  .map(
    ({ name, viewBox, body }) => `export function ${name}(props: IconProps) {
  return (
    <svg viewBox="${viewBox}" fill="none" aria-hidden focusable={false} {...props}>
      ${body.split('\n').map((l) => l.trim()).filter(Boolean).join('\n      ')}
    </svg>
  )
}`,
  )
  .join('\n\n')}
`
}
