/**
 * Shared helpers for the Figma snapshot pipeline.
 *
 * The pipeline is split in two on purpose: `pull.mjs` is the only stage that
 * touches the network, and everything downstream is a pure function of the raw
 * JSON it writes. That split is what makes the rate limit survivable — the
 * expensive call happens once a month, and every later question is answered
 * from disk.
 *
 * See design/README.md for the whole rationale.
 */
import { env } from 'node:process'

export const FILE_KEY = 'gDoteM1ow1AZpSEGSNhpc7'

/**
 * Both roots are overridable so a run can be pointed at a scratch directory —
 * used by the tests, and handy for extracting somewhere else to diff before
 * overwriting the committed snapshot.
 */
const dir = (envVar, fallback) => {
  const override = env[envVar]
  if (!override) return new URL(fallback, import.meta.url)
  return new URL(override.endsWith('/') ? override : `${override}/`, 'file://')
}

/** Raw API responses. Big, ephemeral, gitignored — regenerated by `figma:pull`. */
export const RAW_DIR = dir('FIGMA_RAW_DIR', '../../.figma-raw/')
/** Derived artifacts. Small, committed, the thing everyone actually reads. */
export const DESIGN_DIR = dir('FIGMA_DESIGN_DIR', '../../design/')

/**
 * Figma throttles per endpoint *family* and the budget is inherited across
 * sessions — a fresh container can get a 429 on its first ever call. Retrying
 * in a loop does not help; observed windows have lasted over two hours. So this
 * fails loudly with the one instruction that works: come back later.
 */
export async function figmaFetch(path, { token = env.FIGMA_ACCESS_TOKEN } = {}) {
  if (!token) {
    throw new Error(
      'FIGMA_ACCESS_TOKEN is not set. It lives in the environment config, never in the repo.',
    )
  }

  const res = await fetch(`https://api.figma.com/v1/${path}`, {
    headers: { 'X-Figma-Token': token },
  })

  if (res.status === 429) {
    const err = new Error(
      `Figma returned 429 for /${path}.\n` +
        'This is a real budget, not a per-minute hiccup — windows have lasted 2+ hours and\n' +
        'are inherited across sessions. Do not poll it. Re-run when it clears; everything\n' +
        'else in this pipeline works offline from design/ in the meantime.',
    )
    err.rateLimited = true
    throw err
  }
  if (!res.ok) throw new Error(`Figma returned ${res.status} for /${path}: ${await res.text()}`)

  return res.json()
}

const channel = (v) => Math.round(v * 255).toString(16).padStart(2, '0').toUpperCase()

/**
 * Figma stores opacity as float32, so a designer's 70% arrives as 0.69999999 and
 * would render as B2 rather than the intended B3. Snap to the authored percent.
 */
export function toHex(color, opacity = 1) {
  const rgb = `#${channel(color.r)}${channel(color.g)}${channel(color.b)}`
  const authored = Math.round(opacity * 100) / 100
  return authored >= 0.999 ? rgb : `${rgb}${channel(authored)}`
}

/**
 * CSS gradient angle from Figma's two gradient handles.
 *
 * Handles are normalised to the node's bounding box, so this is only the literal
 * visual angle on a square node — on any other aspect ratio CSS and Figma disagree,
 * which is why the raw handles are kept alongside the computed value.
 */
function gradientAngle([start, end]) {
  const angle = (Math.atan2(end.x - start.x, -(end.y - start.y)) * 180) / Math.PI
  return Math.round(((angle % 360) + 360) % 360)
}

/** Resolves one Figma paint to something a stylesheet can be written from. */
export function resolvePaint(paint) {
  if (paint.visible === false) return null
  const opacity = paint.opacity ?? 1

  if (paint.type === 'SOLID') {
    return { type: 'SOLID', color: toHex(paint.color, paint.color.a ?? opacity) }
  }

  if (paint.type?.startsWith('GRADIENT')) {
    return {
      type: paint.type,
      angle: paint.gradientHandlePositions ? gradientAngle(paint.gradientHandlePositions) : null,
      handles: paint.gradientHandlePositions ?? null,
      stops: (paint.gradientStops ?? []).map((s) => ({
        position: Math.round(s.position * 1e4) / 1e4,
        color: toHex(s.color, s.color.a ?? 1),
      })),
    }
  }

  // Image fills are referenced, never fetched. The file's image fills include
  // personal photographs — see design/README.md §Privacy.
  if (paint.type === 'IMAGE') {
    return { type: 'IMAGE', imageRef: paint.imageRef ?? null, scaleMode: paint.scaleMode ?? null }
  }

  return { type: paint.type }
}

/**
 * Layout and geometry properties worth carrying. Everything omitted here is
 * either derivable, always-default, or vector path data — and vector geometry is
 * the overwhelming bulk of a Figma file, which is what makes the snapshot small
 * enough to commit.
 */
const CARRIED = [
  'layoutMode', 'layoutWrap', 'itemSpacing', 'counterAxisSpacing',
  'paddingLeft', 'paddingRight', 'paddingTop', 'paddingBottom',
  'primaryAxisAlignItems', 'counterAxisAlignItems',
  'primaryAxisSizingMode', 'counterAxisSizingMode',
  'layoutSizingHorizontal', 'layoutSizingVertical',
  'layoutAlign', 'layoutGrow', 'clipsContent',
  'cornerRadius', 'rectangleCornerRadii', 'strokeWeight', 'strokeAlign',
  'opacity', 'blendMode', 'isMask', 'visible',
]

const round = (n) => (typeof n === 'number' ? Math.round(n * 100) / 100 : n)

/**
 * Collapses one raw node to the fields an implementer needs, resolving style and
 * component ids to names so the committed JSON reads on its own without a lookup
 * table beside it.
 */
export function pruneNode(node, { styles = {}, components = {}, componentSets = {} } = {}) {
  const out = { id: node.id, name: node.name, type: node.type }

  const box = node.absoluteBoundingBox
  if (box) {
    out.box = { x: round(box.x), y: round(box.y), w: round(box.width), h: round(box.height) }
  }

  for (const key of CARRIED) {
    const value = node[key]
    if (value === undefined) continue
    // `visible` and `blendMode` are noisy at their defaults; only carry deviations.
    if (key === 'visible' && value === true) continue
    if (key === 'blendMode' && value === 'PASS_THROUGH') continue
    if (key === 'opacity' && value === 1) continue
    out[key] = typeof value === 'number' ? round(value) : value
  }

  const fills = (node.fills ?? []).map(resolvePaint).filter(Boolean)
  if (fills.length) out.fills = fills

  const strokes = (node.strokes ?? []).map(resolvePaint).filter(Boolean)
  if (strokes.length) out.strokes = strokes

  if (node.effects?.length) {
    out.effects = node.effects
      .filter((e) => e.visible !== false)
      .map((e) => ({
        type: e.type,
        radius: round(e.radius),
        offset: e.offset ? { x: round(e.offset.x), y: round(e.offset.y) } : undefined,
        spread: e.spread ? round(e.spread) : undefined,
        color: e.color ? toHex(e.color, e.color.a ?? 1) : undefined,
      }))
    if (!out.effects.length) delete out.effects
  }

  // The token layer. Style *names* are the whole reason this project can read its
  // design system without the Enterprise-only Variables API, so resolve them here
  // rather than leaving opaque ids in the snapshot.
  const refs = node.styles ?? {}
  const named = {}
  for (const [slot, id] of Object.entries(refs)) {
    if (styles[id]?.name) named[slot] = styles[id].name
  }
  if (Object.keys(named).length) out.styles = named

  if (node.type === 'TEXT') {
    if (node.characters) out.characters = node.characters
    if (node.style) {
      const { fontFamily, fontSize, fontWeight, lineHeightPx, letterSpacing, textAlignHorizontal,
        textAlignVertical, textCase, textDecoration } = node.style
      out.text = {
        fontFamily, fontSize, fontWeight,
        lineHeightPx: round(lineHeightPx),
        letterSpacing: round(letterSpacing),
        textAlignHorizontal, textAlignVertical, textCase, textDecoration,
      }
      for (const k of Object.keys(out.text)) if (out.text[k] === undefined) delete out.text[k]
    }
  }

  if (node.componentId) {
    out.componentId = node.componentId
    const meta = components[node.componentId]
    if (meta?.name) out.component = meta.name
    if (meta?.componentSetId && componentSets[meta.componentSetId]?.name) {
      out.componentSet = componentSets[meta.componentSetId].name
    }
  }
  if (node.componentPropertyDefinitions) {
    out.componentPropertyDefinitions = node.componentPropertyDefinitions
  }
  if (node.componentProperties) out.componentProperties = node.componentProperties

  if (node.children?.length) {
    out.children = node.children.map((child) =>
      pruneNode(child, { styles, components, componentSets }),
    )
  }

  return out
}

/** Depth-first walk over a raw or pruned tree. */
export function* walk(node) {
  yield node
  for (const child of node.children ?? []) yield* walk(child)
}

/**
 * Counts how often each named paint and text style is used, and with which
 * resolved value. The dominant value is the token; a style resolving to more
 * than one value means the file has drifted and is worth surfacing.
 */
export function collectTokens(root, styles) {
  const fills = new Map()
  const text = new Map()

  const bump = (map, name, value) => {
    if (!map.has(name)) map.set(name, new Map())
    const counts = map.get(name)
    counts.set(value, (counts.get(value) ?? 0) + 1)
  }

  for (const node of walk(root)) {
    const refs = node.styles ?? {}

    if (refs.fill && styles[refs.fill]) {
      for (const paint of node.fills ?? []) {
        if (paint.type !== 'SOLID' || paint.visible === false) continue
        bump(fills, styles[refs.fill].name, toHex(paint.color, paint.opacity ?? paint.color.a ?? 1))
      }
    }

    if (refs.text && styles[refs.text] && node.style) {
      const { fontSize, lineHeightPx, fontWeight } = node.style
      // Line height arrives as float32 noise (20.00004 for an authored 20), which
      // would otherwise land verbatim in the token table.
      bump(text, styles[refs.text].name, `${round(fontSize)}/${round(lineHeightPx)}/${fontWeight}`)
    }
  }

  return { fills, text }
}

/** Census of the geometry values actually used, so primitives stop being guessed. */
export function collectGeometry(root) {
  const census = { cornerRadius: {}, itemSpacing: {}, paddingLeft: {}, paddingTop: {} }

  for (const node of walk(root)) {
    for (const key of Object.keys(census)) {
      const value = node[key]
      if (typeof value !== 'number') continue
      census[key][value] = (census[key][value] ?? 0) + 1
    }
  }

  // Descending by use — the most-used value is the one a new component should take.
  return Object.fromEntries(
    Object.entries(census).map(([key, counts]) => [
      key,
      Object.entries(counts)
        .map(([value, n]) => ({ value: Number(value), n }))
        .sort((a, b) => b.n - a.n),
    ]),
  )
}

export const total = (counts) => [...counts.values()].reduce((a, b) => a + b, 0)
export const dominant = (counts) => [...counts.entries()].sort((a, b) => b[1] - a[1])[0][0]
export const isLegacy = (name) => name.includes('(OLD)')

/** Filesystem-safe, stable, and readable — `v2 / Component / Button` -> `v2-component-button`. */
export function slug(name) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80) || 'unnamed'
}
