-- 061: the ride chat unread watermark, and the boolean behind the header dot.
--
-- Linear PD-120; the epic is PD-115 and the proposal is
-- openspec/changes/add-ride-chat-unread/.
--
-- `Ride - Ride plan - Sub pages` (2375:9114) and `Ride - Crew (Riders)`
-- (2375:9212) both draw a 16×16 `v2 / Component / Notification` in `Warning/100`
-- on the chat-bubble button, visible in both — while the same component sits
-- `[hidden]` on those frames' back and Options buttons. Nothing in the app has
-- ever recorded what a rider has read of a chat, so the dot could not be drawn:
-- `RideHeader`'s docstring says a badge that is always absent is
-- indistinguishable from one that is broken.
--
-- ---------------------------------------------------------------------------
-- 015's model, transferred — and the two places it is deliberately NOT copied
-- ---------------------------------------------------------------------------
-- `feed_reads` is a per-audience read watermark: one row per (rider, audience
-- they have joined), so the row count is bounded by MEMBERSHIP rather than by
-- content. 015's header carries the rejected alternative — a row per (rider,
-- item) seen — and every word of that argument holds here and then some: a chat
-- is the one table in this schema with no natural ceiling, and a read-receipt
-- table would put that unbounded growth on the WRITE path, generated by
-- scrolling.
--
-- The cost is 015's cost, inherited rather than new: a watermark can only ever
-- say "everything older than T is read", never a prefix. That is honest for a
-- chat in a way it was not for the newest-first deck — a thread is read
-- oldest-first to the end, so a rider with the screen open has read to the end.
--
-- Two things are NOT copied, and both are stated here because copying them is
-- the cheaper mistake:
--
--   * **`unique nulls not distinct` is absent, on purpose.** 015 needs it
--     because `feed_reads.club_id IS NULL` *means* something — the app-wide feed
--     — so under a plain UNIQUE every visit would insert another app-wide row
--     and the upsert would never find a conflict to update. There is no
--     "app-wide ride". Both key columns here are NOT NULL, so a real PRIMARY KEY
--     is available, and a clause that expresses a rule this table does not have
--     is worse than no clause: the next reader infers a nullable audience.
--
--   * **`last_read_at` is imposed by a trigger** rather than trusted from the
--     client the way `feed_reads.last_seen_at` is. See §3 — that one is a
--     defect, not a precedent.

-- ---------------------------------------------------------------------------
-- §1. The table
-- ---------------------------------------------------------------------------
--
-- The primary key doubles as the `on conflict` target the upsert names, which is
-- why no separate unique constraint appears.
--
-- **The key leads with `user_id` and that ordering is load-bearing**, not
-- cosmetic: 029 asserts that no foreign key into `profiles` lacks a
-- leading-column index, derived from `pg_constraint` rather than from a list, so
-- `(ride_id, user_id)` would fail the suite. It also suits the reader in §4,
-- which knows both columns.

create table public.ride_reads (
  user_id      uuid references public.profiles(id) on delete cascade not null,
  ride_id      uuid references public.rides(id) on delete cascade not null,
  last_read_at timestamptz default now() not null,

  primary key (user_id, ride_id)
);

alter table public.ride_reads enable row level security;

comment on table public.ride_reads is
  'Per-ride chat read watermark (061). One row per (rider, ride); last_read_at is server-imposed by a trigger, never client-supplied. Bounded by crew membership, not by message volume — see 061 for why this is not a per-message read-receipt table, and for why nobody but the row''s owner may read it.';

-- For the cascade, not for a screen — the same reason 029 indexed every FK into
-- `profiles` and 011 indexed `postcard_comments.author_id`. The primary key
-- leads with `user_id`, so a delete of one RIDE has no index to reach its
-- watermarks by and would sequentially scan a table whose size is riders ×
-- rides-they-have-opened. Deleting a ride is a shipped rider action (PD-101),
-- not a maintenance event.
--
-- 015 has the same gap on `feed_reads.club_id` and is not fixed here.
create index ride_reads_ride_id_idx on public.ride_reads (ride_id);

-- ---------------------------------------------------------------------------
-- §2. Policies — own rows only, for a chat the rider can actually read
-- ---------------------------------------------------------------------------
--
-- SELECT is `user_id = auth.uid()` and nothing wider, and that narrowness is a
-- DECISION rather than a default. A watermark is behavioural personal data about
-- an identified person — when they last looked at a named conversation — and a
-- ride's chat has a small, named audience, so "the organizer can see I read at
-- 03:40" is a fact about one rider on one night. **This app has no read
-- receipts**, and the policy is where that is enforced rather than merely
-- unbuilt: the data to draw a "seen by" row is unreachable, so adding one is a
-- migration and a conversation, not an afternoon.
--
-- ---------------------------------------------------------------------------
-- The write predicate is the full intersection — and 034's reason is NOT why
-- ---------------------------------------------------------------------------
-- The audience conjunct is the same intersection 034's SELECT policy uses: an
-- EXISTS against `rides` evaluated under the CALLER's own row security, AND
-- `private.is_ride_crew(ride_id)`.
--
-- **034's stated reason does not transfer, and inheriting it would be worse than
-- inheriting nothing.** That header is about READING: a `security definer`
-- helper answering only "do I hold a crew row" steps past the block and
-- private-club arms of the `rides` policy, so a SELECT policy using it alone
-- hands an ex-club-member somebody else's thread. A WITH CHECK grants no reads.
-- A watermark row is returned only to its own owner, it contains a ride id the
-- writer supplied and a timestamp, and §4 never consults it to decide what may
-- be read. Writing "the crew helper alone is a leak" in this file would be
-- asserting a guarantee the mechanism does not give — and a comment whose stated
-- reason is false is how the next session removes the conjunct.
--
-- What DOES transfer, unchanged, is 015 §2's: without an audience predicate the
-- foreign key turns an INSERT into an existence oracle, because a nonexistent
-- ride id raises 23503 while an existing-but-invisible one succeeds. So *some*
-- predicate is required. The choice of the full intersection over the crew
-- helper alone rests on three things:
--
--   1. **Audience equality.** The watermark's audience is then exactly the
--      chat's, so no row can ever assert that a rider read a thread they cannot
--      open. With the helper alone, a rider who blocked the organizer keeps
--      writing watermarks for a chat that returns them nothing.
--   2. **The instrument.** `private.is_ride_crew`'s own comment says it is "half
--      of a conjunction by design; on its own it is a leak". Using it as a sole
--      conjunct ANYWHERE establishes by example that it is usable alone, and the
--      next child table of `rides` copies the shape rather than the reasoning —
--      which is exactly how 034's first draft copied `is_club_member` and
--      shipped a leak.
--   3. **It costs nothing measurable.** A rider who satisfies the crew conjunct
--      and fails the visibility one already gets `null` from `getRide` and a
--      404, so no screen issues the write. The conjunct refuses a request the
--      app never makes; its whole value is against a direct PostgREST call with
--      the publishable key, which ships in the bundle.

create policy "Riders see only their own chat watermarks"
  on public.ride_reads for select to authenticated
  using (user_id = auth.uid());

create policy "Riders mark only their own ride chats read"
  on public.ride_reads for insert to authenticated
  with check (
    user_id = auth.uid()
    and exists (select 1 from public.rides r where r.id = ride_reads.ride_id)
    and private.is_ride_crew(ride_id)
  );

-- The upsert's UPDATE arm.
--
-- **USING is `user_id = auth.uid()` alone, and the asymmetry is deliberate.**
-- USING scopes which rows may be REACHED and WITH CHECK what they may BECOME.
-- Putting the audience conjuncts in USING as well would mean a rider who has
-- since left a private club cannot reach their own stale row — which changes
-- nothing they can do (the WITH CHECK refuses the write either way) and makes
-- the policy harder to read than the rule it encodes.
create policy "Riders advance only their own chat watermarks"
  on public.ride_reads for update to authenticated
  using (user_id = auth.uid())
  with check (
    user_id = auth.uid()
    and exists (select 1 from public.rides r where r.id = ride_reads.ride_id)
    and private.is_ride_crew(ride_id)
  );

-- No DELETE policy and no DELETE grant.
--
-- 015 §2 gives the reason as "leaving a club cascades the row away via the FK,
-- so the only deletion that has a meaning already happens without a grant".
-- **That sentence is wrong and must not be carried across**: `feed_reads.club_id`
-- references `clubs(id)`, so the cascade fires when the CLUB is deleted, not
-- when a membership ends. The conclusion survives; the reason has to be the
-- honest one.
--
-- Which is: deleting a watermark means "mark this unread again", and no screen
-- draws that. Leaving a ride's crew leaves the row standing, inert, until the
-- ride or the rider is deleted — and rejoining reuses it, so messages sent while
-- the rider was away read as unread, which is right.
--
-- No participation-gate trigger either, following 023's own stated reason for
-- excluding `feed_reads`: a watermark produces nothing anyone sees. A rider who
-- has not consented cannot be crew in the first place — the gate is on `rides`
-- and `ride_members` — so the WITH CHECK above already refuses them. The gate
-- trigger count must therefore read the same after this migration as before it.

-- ---------------------------------------------------------------------------
-- §3. The clock — both sides of the comparison must come from one
-- ---------------------------------------------------------------------------
--
-- `last_read_at` is imposed by a BEFORE INSERT OR UPDATE trigger. Whatever the
-- client sent is discarded.
--
-- **The argument is not tamper-resistance.** A rider who forges their own
-- watermark suppresses their own dot, which is self-harm and nobody else's
-- problem. It is that §4 compares `last_read_at` against
-- `ride_messages.created_at`, and 034 §4b makes THAT server-generated — by
-- withholding the column from the INSERT grant — precisely so a device clock can
-- never order a conversation. Taking the other operand from the phone puts one
-- clock on each side of the comparison: a handset running ten minutes fast
-- silently marks read every message arriving in the next ten minutes, and a slow
-- one re-lights the dot on messages already seen. Nothing errors, nothing logs,
-- and the wrong answer follows the device rather than the account.
--
-- **`markClubSeen` and `markFeedSeen` both send `new Date().toISOString()` into
-- `feed_reads.last_seen_at`, which `club_unread_counts()` compares against
-- `postcards.created_at` and `rides.created_at`. That is this defect, shipped.**
-- It is a different table on a shipped path and is not fixed here — but this
-- table must not copy the pattern on the grounds that the existing one does.
--
-- **A DEFAULT cannot do this job**, which is the trap worth naming: a default
-- applies only when the column is OMITTED, and PostgREST will happily name it.
--
-- **Nor is `034` §4b's mechanism — withholding the column grant — the right tool
-- here, and the obvious reason for that is FALSE.** It is tempting to write "the
-- upsert's UPDATE arm must name `last_read_at`, so revoking the grant would fail
-- 42501". It would not: PostgREST builds `on conflict … do update set` over the
-- columns present in the request BODY, so a client that omits the column needs
-- no privilege on it and nothing raises. Writing that sentence would be the
-- second false justification in this file, and §2 already explains why a comment
-- asserting a mechanism that does not fire is how the next session removes it.
--
-- The real reason is narrower: with the column absent from the body, what
-- ADVANCES the value on the UPDATE arm is this trigger, and what makes the
-- statement reach the trigger at all is PostgREST's SET-list construction — an
-- external tool's behaviour, not a database guarantee, and one the RLS suite
-- cannot observe because it speaks SQL rather than HTTP. So `markRideChatSeen`
-- sends the column, the table-level grant stays to permit it, and the trigger
-- makes the value true regardless. Two visible mechanisms, neither inferred.
--
-- Withholding `update (last_read_at)` on top of the trigger would be a real
-- hardening — refusal at the door for a client that names the column, on top of
-- a value it cannot influence — and it is deliberately NOT taken here because
-- nothing in this repo could gate it: the only test that would catch it breaking
-- is a live PostgREST round trip, which no CI job makes. Recorded rather than
-- silently declined.
--
-- **Both arms, not just INSERT.** A BEFORE INSERT trigger alone would impose the
-- value on a rider's first visit to a ride and keep the client's on every visit
-- after — which is the worst of the three available behaviours, because it works
-- on fresh rows and drifts in use.
--
-- `security invoker` (the default): it reads nothing and writes nothing but
-- NEW, so it needs no elevated rights, and an invoker function raises no
-- `authenticated_security_definer_function_executable` advisor. EXECUTE is
-- revoked anyway, matching `public.enforce_participation_gate()` — Postgres
-- checks EXECUTE on a trigger function at CREATE TRIGGER time, not at fire time,
-- which is what makes that revoke free rather than breaking.

create function public.stamp_ride_read()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.last_read_at := now();
  return new;
end;
$$;

comment on function public.stamp_ride_read() is
  'Imposes ride_reads.last_read_at from the server clock on INSERT and UPDATE (061). Not tamper-resistance — it is that the value is compared against ride_messages.created_at, which 034 makes server-generated, and a comparison spanning two clocks is wrong in a way nothing logs.';

revoke all on function public.stamp_ride_read() from public, anon, authenticated;

create trigger stamp_ride_read
  before insert or update on public.ride_reads
  for each row
  execute function public.stamp_ride_read();

-- ---------------------------------------------------------------------------
-- §4. The dot's answer
-- ---------------------------------------------------------------------------
--
-- SECURITY INVOKER, deliberately, and it is what makes it safe to publish in
-- `public` where PostgREST reaches it. The function runs as the caller, so 034's
-- SELECT policy applies to `ride_messages` inside it — all three of its
-- conjuncts, including the symmetric block arm on the author. So a blocked
-- rider's message cannot light anybody's dot, and no block filter appears here,
-- in `lib/data/` or in the component: one copy of the rule, in the policy that
-- already owns it. A ride the caller cannot see answers `false`, identically to
-- a ride that does not exist and identically to a quiet chat, so the RPC is not
-- an existence oracle. Contrast 005/006, which moved their SECURITY DEFINER
-- helpers into `private` precisely because those COULD disclose.
--
-- **Boolean, not a count, and singular, not plural.** The design draws a dot:
-- `NotificationDot`'s docstring records that the Figma component carries a
-- `Notifications` text property with no text layer rendering it, and that
-- `v2 / Component / Counter` — the component that does draw a number — answers a
-- different question. The boolean is also the better computation, which is the
-- one place this file improves on 015 rather than copying it: 015 §4 caps each
-- subquery at `limit 100` because a COUNT must visit every qualifying row, and
-- the UI shows `99+` above 99 anyway. An `exists` short-circuits on the first
-- row, so this is genuinely O(1) in thread length through
-- `ride_messages_ride_id_idx (ride_id, created_at, id)` that 034 already
-- created, with no cap to justify and no number for somebody to render later.
--
-- Singular because N is 1 by construction here: the dot is drawn on one ride's
-- header, and the ride plan and crew screens are each already reading exactly
-- that ride. A plural `ride_unread_counts()` mirroring 015 would be an RPC with
-- no caller, which is the same artifact as a control that renders and does
-- nothing. Going plural later is a new function rather than a signature change,
-- so nothing here forecloses the Rides-tab rollup — 015's own argument for why
-- choosing a watermark did not foreclose `postcard_views`.
--
-- **`author_id <> auth.uid()` — your own messages never light your own dot.**
-- Reachable with no race at all: send, tap back. Excluding them makes the answer
-- correct independently of whether the watermark advanced first, which is worth
-- more than a correctness that depends on winning a race with a navigation.
-- 015 does NOT do this, and the divergence is deliberate rather than an
-- oversight: `club_unread_counts()` does not exclude the reader's own postcards,
-- and since a postcard is authored from `/postcards/new` rather than from inside
-- a club, that counter genuinely can badge a club for the reader's own post.
-- That is a candidate defect in 015, recorded here and not fixed here.
--
-- **Three coalesce arms, where 015 has two, and the third is load-bearing
-- today.** 015 uses `coalesce(last_seen_at, joined_at)` so that joining a
-- five-year-old club does not badge it with everything ever posted; that arm
-- transfers unchanged. The third exists because 034 §1 establishes that the
-- organizer may hold NO `ride_members` row at all — `createRide` writes it as a
-- second round trip with no transaction, so the state is reachable on demand
-- rather than only on error, and `enforce-creator-membership` is unshipped. With
-- two arms that rider's comparison point is NULL, every `created_at > NULL` is
-- NULL, `exists` is false, and **the host is the one member of the crew whose
-- dot never lights** — silently, for ever, on their own ride. It is the failure
-- 034 avoided by putting an organizer arm in `is_ride_crew`, arriving through a
-- different door.
--
-- `rides.created_at` rather than a `'-infinity'` sentinel: it is a real column
-- that always exists, no message can predate its own ride, and it says what it
-- means. **The arm stays if `enforce-creator-membership` ever lands** — a
-- privileged path can still remove the row, and an invariant enforced twice is
-- cheap when the alternative is a host who is never notified.
--
-- **All three arms are on the DATABASE's clock**, which is the §3 rule reaching
-- past the column it was written for: 048 made `ride_members.joined_at`
-- server-owned and 045 did the same for `rides.created_at`. A comparison that
-- silently spanned two clocks through the *fallback* would have been the same
-- defect wearing a fallback's clothes.
--
-- **Arm two is read under the caller's own RLS and can therefore go missing**,
-- which the priority order does not say on its own. 009 gates `ride_members`
-- SELECT behind an EXISTS on `rides` before its `user_id = auth.uid()` arm, so a
-- caller who cannot read their own membership row falls through to arm three.
-- That degrades in the safe direction — "since the ride existed" over-reports
-- unread rather than hiding a message — and it is the direction §3 already picks
-- when it has to pick one. Stated because the alternative is discovering it as a
-- badge that will not clear.

create function public.ride_has_unread(ride uuid)
returns boolean
language sql
stable
security invoker
set search_path = ''
as $$
  select exists (
    select 1
    from public.ride_messages m
    where m.ride_id = ride
      and m.author_id <> auth.uid()
      and m.created_at > coalesce(
        (select w.last_read_at from public.ride_reads w
          where w.user_id = auth.uid() and w.ride_id = ride),
        (select k.joined_at from public.ride_members k
          where k.ride_id = ride and k.user_id = auth.uid()),
        (select d.created_at from public.rides d where d.id = ride)
      )
  );
$$;

comment on function public.ride_has_unread(uuid) is
  'Does this ride''s chat hold a message the caller has not read (061)? SECURITY INVOKER, so 034''s SELECT policy decides what counts — blocks and ride visibility included. Excludes the caller''s own messages. Falls back to ride_members.joined_at, then rides.created_at, the last of which is what keeps an organizer holding no crew row from being the one rider whose dot never lights.';

-- ---------------------------------------------------------------------------
-- §5. Grants
-- ---------------------------------------------------------------------------
--
-- RLS needs BOTH a table grant and a permitting policy. Note what is not
-- granted: DELETE on the table (§2), and anything at all to `anon` —
-- decision #1.
--
-- UPDATE is granted at table level rather than per column, unlike 044/046 on
-- `postcards`. There is nothing here to withhold: `user_id` and `ride_id` are
-- pinned by the WITH CHECK, and `last_read_at` is pinned by §3's trigger, so a
-- column-level list would restate what two other mechanisms already enforce and
-- would break the upsert's UPDATE arm besides.

revoke all on public.ride_reads from anon, authenticated;
grant select, insert, update on public.ride_reads to authenticated;

revoke all on function public.ride_has_unread(uuid) from public, anon;
grant execute on function public.ride_has_unread(uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- §Verification — run these against the project after applying, do not assume
-- ---------------------------------------------------------------------------
--
-- Expected: 3 (select, insert, update — no delete)
--   select count(*) from pg_policies where tablename = 'ride_reads';
--
-- Expected: 0 — every policy must be `to authenticated`
--   select count(*) from pg_policies
--    where tablename = 'ride_reads' and roles::text[] <> array['authenticated'];
--
-- Expected: 0 — anon holds nothing
--   select count(*) from information_schema.role_table_grants
--    where table_name = 'ride_reads' and grantee = 'anon';
--
-- Expected: f — `authenticated` cannot delete a watermark.
--
-- **Scoped to the grantee on purpose.** The unscoped form ("no DELETE grant on
-- the table at all") returns 2 and always will: `postgres` owns the table and
-- `service_role` holds everything by Supabase default, on this and every other
-- table in the schema. 015's footer was written unscoped, read as a failure
-- against a correct database, and is the reason the suite asserts the privilege
-- rather than counting grant rows.
--   select has_table_privilege('authenticated', 'public.ride_reads', 'delete');
--
-- Expected: t — the upsert's UPDATE arm needs it
--   select has_table_privilege('authenticated', 'public.ride_reads', 'update');
--
-- Expected: 0 — there is no `nulls not distinct` index here, because there is
-- no nullable key column for one to apply to. This is the assertion that would
-- catch 015's clause being copied in by reflex.
--   select count(*) from pg_index i join pg_class c on c.oid = i.indexrelid
--    where i.indrelid = 'public.ride_reads'::regclass and i.indnullsnotdistinct;
--
-- Expected: f — the reader is INVOKER, not DEFINER. If it ever flips, it stops
-- obeying the blocks and the ride-visibility arms 034's policy applies, and
-- starts answering `true` for threads the caller cannot read.
--   select prosecdef from pg_proc where proname = 'ride_has_unread';
--
-- Expected: 2 — the trigger fires on INSERT and on UPDATE. `tgtype` bit 2 is
-- BEFORE, bit 4 INSERT, bit 16 UPDATE.
--   select (tgtype & 4 > 0)::int + (tgtype & 16 > 0)::int from pg_trigger
--    where tgname = 'stamp_ride_read' and not tgisinternal;
--
-- Expected: unchanged from before this migration — ride_reads does NOT join the
-- participation gate. Ten at the time of writing.
--   select count(*) from pg_trigger
--    where tgname = 'enforce_participation_gate' and not tgisinternal;
--
-- Expected: 9 advisors, with auth_leaked_password_protection still the only
-- outstanding one. A tenth means a revoke did not land, or the reader was
-- written `definer`.
--   mcp__Supabase__get_advisors  type=security
